[package]
name = "rmc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
rmc-core = { path = "../rmc-core" }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
notify = "6.1.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.5", features = ["trace", "cors"] }
jsonwebtoken = "9.3"
chrono = "0.4"
