[package]
name = "rmc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["image", "tokio", "advanced"] }
rmc-core = { path = "../rmc-core" }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", features = ["full", "macros"] }
serde_json = "1.0"
rmc-player-engine = { path = "../rmc-player-engine" }
